#!/usr/bin/with-contenv bash

source /ctx/bin/functions.sh
logging "[init_manager] ICON2 Configuration"

cd /ctx
python3 init_manager.py

if [[ $? != 0 ]]; then
    logging "[init_manager] abnormal terminated. shutting down container"
    s6-svscanctl -t /var/run/s6/services
    sleep 5
fi
