#!/usr/bin/with-contenv bash

## TEST start
echo "[init_manager] ICON2 Configuration"

cd /ctx
python3 init_manager.py

if [[ $? != 0 ]]; then
    echo "[init_manager] abnormal terminated. shuting down container"
    s6-svscanctl -t /var/run/s6/services
    sleep 5
fi
