#!/usr/bin/with-contenv bash

export $(cat /goloop/.env)
source /ctx/bin/functions.sh

if [[ "${GOLOOP_CONFIG}" != "" && ! -f "${GOLOOP_CONFIG}" ]]; then
    UNSET="GOLOOP_CONFIG"
    CMD="goloop server save ${GOLOOP_CONFIG}"
    logging "generate ${GOLOOP_CONFIG} - ${CMD}"
    bash -c "unset $UNSET ; $CMD 2>&1 | tee -a ${BOOTING_LOG}"
fi

logging "Start goloop server (${LOG_OUTPUT_TYPE}, ${BASE_DIR}, ${GOLOOP_CONFIG})"

cd ${BASE_DIR}
source /goloop/venv/bin/activate
if [[ "$LOG_OUTPUT_TYPE" == "file" ]]; then
#    goloop server start 2>&1 >> ${LOGFILE}
    goloop server start 2>> ${LOGFILE}
elif [[ "$LOG_OUTPUT_TYPE" == "debug" ]]; then
    goloop server start
else
    goloop server start 2>&1 | tee -a ${LOGFILE}
fi
