#!/usr/bin/with-contenv bash

#source /goloop/.env
#export $(cat /goloop/.env)
#export BASE_DIR=${BASE_DIR:-"/goloop"}
#export GOLOOP_CONFIG=${GOLOOP_CONFIG:-"${BASE_DIR}/config/server.json"}
#export LOG_OUTPUT_TYPE=${LOG_OUTPUT_TYPE:-"file"}
#export BASE_DIR=${BASE_DIR:-"/goloop"}
export $(cat /goloop/.env)
source /ctx/functions.sh

if [[ "${GOLOOP_CONFIG}" != "" && ! -f "${GOLOOP_CONFIG}" ]]; then
    UNSET="GOLOOP_CONFIG"
    CMD="goloop server save ${GOLOOP_CONFIG}"
#    echo "generate ${GOLOOP_CONFIG}" >> ${LOGFILE}
    logging "generate ${GOLOOP_CONFIG} - ${CMD}"
    bash -c "unset $UNSET ; $CMD 2>&1 | tee -a ${BOOTING_LOG}"
fi

#echo ">>>> Starting goloop server (${LOG_OUTPUT_TYPE}, ${BASE_DIR}, ${GOLOOP_CONFIG}}) <<<<<" >> ${BASE_DIR}/logs/booting.log
logging "Start goloop server (${LOG_OUTPUT_TYPE}, ${BASE_DIR}, ${GOLOOP_CONFIG})"

cd ${BASE_DIR}
source /goloop/venv/bin/activate
if [[ "$LOG_OUTPUT_TYPE" == "file" ]]; then
#    goloop server start 2>&1 >> ${LOGFILE}
    goloop server start 2>> ${LOGFILE}
else
    goloop server start 2>&1 | tee -a ${LOGFILE}
fi
